spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  application:
    name: service-monitor-first
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.135:8848
  config:
    import:
      - optional:nacos:config-monitor.yaml?refreshEnabled=true